name: Publier une nouvelle version

on:
  push:                                     # Déclencheur du workflow.
    branches:
      - main                                # Le workflow s'exécute uniquement sur des pushs dans la branche `main`.

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      # Vérifier et cloner le dépôt.
      - name: Checkout repository
        uses: actions/checkout@v4           # Utilise l'action officielle pour cloner le dépôt dans l'environnement.

      # Exécuter l'action composite.
      - name: Exécuter l'action composite
        uses: ./action-directory/           # Appelle l'action personnalisée définie dans `action-directory`.
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Injecte le secret dans l'environnement.