name: Publier une nouvelle version

on:
  push:                                     
    branches:
      - main                               

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      # Vérifier et cloner le dépôt.
      - name: Checkout repository
        uses: actions/checkout@v4           

      # Exécuter l'action composite.
      - name: Exécuter l'action composite
        uses: ./action-directory/
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  